name: Build Kivy App for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install kivy requests stripe python-dotenv

      - name: Build Android APK
        run: |
          # Assuming buildozer is installed and configured properly
          buildozer android debug

      - name: Check APK file
        run: |
          if [ ! -f ./bin/*.apk ]; then
            echo "No APK file found"
            exit 1
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: ./bin/*.apk
